### ISSUE TITLE
What is the minimum Android version supported?

### ISSUE THREAD

**Issue by BurkusCat** [jfversluis/Plugin.Maui.Audio#74]
I was testing my app on Android version 5 and got this exception. What is the lowest version of Android that this plugin is expected to run on? :)

```
**System.IO.DirectoryNotFoundException:** 'Could not find a part of the path '/data/data/uk.co.burkus.catlists/files/Documents/cache0.wav'.'

**System.IO.DirectoryNotFoundException:** 'Could not find a part of the path '/data/data/uk.co.burkus.catlists/files/Documents/cache0.wav'.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Could not find a part of the path '/data/data/uk.co.burkus.catlists/files/Documents/cache0.wav'.
[mono-rt]    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
[mono-rt]    at Interop.CheckIo(Error error, String path, Boolean isDirError)
[mono-rt]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[mono-rt]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[mono-rt]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
[mono-rt]    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[mono-rt]    at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[mono-rt]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[mono-rt]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[mono-rt]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
[mono-rt]    at System.IO.File.Create(String path, Int32 bufferSize)
[mono-rt]    at System.IO.File.Create(String path)
[mono-rt]    at Plugin.Maui.Audio.AudioPlayer.PreparePlayerLegacy(Stream audioStream)
[mono-rt]    at Plugin.Maui.Audio.AudioPlayer..ctor(Stream audioStream)
[mono-rt]    at Plugin.Maui.Audio.AudioManager.CreatePlayer(Stream audioStream)
[mono-rt]    at Catlists.ViewModels.PlayGameViewModel.CreateStandardAudioPlayer(String audioFilePath, Single volume) in C:\Projects\cat-lists\src\Catlists\ViewModels\PlayGameViewModel.cs:line 251
[mono-rt]    at Catlists.ViewModels.PlayGameViewModel.OnNavigatedTo(NavigationParameters parameters) in C:\Projects\cat-lists\src\Catlists\ViewModels\PlayGameViewModel.cs:line 141
[mono-rt]    at Burkus.Mvvm.Maui.LifecycleEventUtility.TriggerOnNavigatedTo(Object bindingContext, NavigationParameters navigationParameters)
[mono-rt]    at Burkus.Mvvm.Maui.NavigationService.<HandleNavigation>d__14`1[[Catlists.Pages.PlayGamePage, Catlists, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
[mono-rt]    at Burkus.Mvvm.Maui.NavigationService.<Push>d__1`1[[Catlists.Pages.PlayGamePage, Catlists, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
[mono-rt]    at Catlists.ViewModels.HomeViewModel.Play() in C:\Projects\cat-lists\src\Catlists\ViewModels\HomeViewModel.cs:line 87
[mono-rt]    at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask) in /_/src/CommunityToolkit.Mvvm/Input/AsyncRelayCommand.cs:line 351
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Jav
```

**Comment by bijington** [comment]
There shouldn't be anything that prevents the library from working on Android 5. The error message suggests that the file doesn't exist at the path specified. Can you confirm whether that is the case?

**Comment by BurkusCat** [comment]
So the error message says it is trying to play "cache0.wav" in Documents. But, I'm actually just trying to play a file in my apps "Resources/Raw" folder. I presume "cache0.wav" is something that this library does to play files?

This is roughly code I'm using (minus any methods etc):
``` c#
        var audioStream = await fileSystem.OpenAppPackageFileAsync("song.wav");
        var audioPlayer = audioManager.CreatePlayer(audioStream);
        audioPlayer.Volume = 0.5f;
        audioPlayer.Play();
```

The above code works on the newer versions of iOS/Android. I was testing my app on Android 5 to see if it worked okay on a very low version and I hit this error.

**Comment by bijington** [comment]
Oh yes good spot! This is the code where it does that:

![image](https://github.com/jfversluis/Plugin.Maui.Audio/assets/17139988/648aae7d-3b56-4a89-922c-af46db9b080b)

As a test you could try running this code before calling play:

```csharp
var documentsPath Environment.GetFolderPath(Environment.SpecialFolder.Personal);

if (Directory.Exists(documentsPath) is false)
{
    Directory.Create(documentsPath);
}
```

The code assume that directory exists but perhaps on old versions it doesn't.

**Comment by BurkusCat** [comment]
Your suggested code worked around the issue on Android 5. Android 6 didn't require the below code, it doesn't crash.
``` csharp
var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);

if (Directory.Exists(documentsPath) is false)
{
    Directory.CreateDirectory(documentsPath);
}
```

**Comment by bijington** [comment]
Great thanks for confirming. TBH I don't see any harm in us adding the code in to create the directory if it doesn't exist

**Comment by jfversluis** [comment]
Thanks for the collaboration here @BurkusCat!

Merging this PR now, I do think it will be part of the next major release that targets .NET 8.
