### ISSUE TITLE
FailedToLoadAudioException

### ISSUE THREAD

**Issue by ts69repo** [jfversluis/Plugin.Maui.Audio#85]
mp3 in Raw folder of MAUI project

IAudioPlayer fplayer = AudioManager.Current.CreatePlayer(await FileSystem.OpenAppPackageFileAsync(filename));

Plugin.Maui.Audio.FailedToLoadAudioException: Unable to create AVAudioPlayer from data.
   at Plugin.Maui.Audio.AudioPlayer..ctor(Stream audioStream)
   at Plugin.Maui.Audio.AudioManager.CreatePlayer(Stream audioStream)

Xcode 15.0.1, iOS 17, CarPlay App

Inside this class:
public class MyCPAppSceneDelegate : CPTemplateApplicationSceneDelegate

**Comment by ts69repo** [comment]
It looks like the mp3 file was corrupt. After changing the file it is working as expected.
